### ISSUE TITLE
[RoleOptionsProvider] Default Role not visible in MembersGroup object

### ISSUE THREAD

**Issue by scrummer** [dachcom-digital/pimcore-members#201]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In [RoleOptionsProvider:49](https://github.com/dachcom-digital/pimcore-members/blob/master/src/CoreExtension/Provider/RoleOptionsProvider.php#L49) the `ROLE_USER`-role is proposed as default role to be available for all group objects.
This method tho is never called and therefore there are no available roles to associate with groups (unless you configure some explicitly).

### With no roles configured
```yaml
security:    
    role_hierarchy:
        # Pimcore admin  // DO NOT CHANGE!
        ROLE_PIMCORE_ADMIN: [ROLE_PIMCORE_USER]
```
Result:
![image](https://github.com/user-attachments/assets/5a4be90a-1114-442d-9413-72ae84a2ef85)

### With a user-defined role
```yaml
security:
    role_hierarchy:
        # Pimcore admin  // DO NOT CHANGE!
        ROLE_PIMCORE_ADMIN: [ROLE_PIMCORE_USER]
        SOME_SPECIAL_ROLE: [ROLE_USER]
```
Result:
![image](https://github.com/user-attachments/assets/c1cc9a4a-cbd7-461a-a19f-f1c0e33bbbdd)
