### ISSUE TITLE
[Members2] Apply predefined Groups to new User

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-members#29]
After a registration, user should automatically get applied to specific groups:

```yaml
 user:
    initial_groups:
        - 'your-group-name'
        - 'your-second-group-name'
```
