### ISSUE TITLE
[Auth] Logout does not work in production mode

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#38]
Ever had the issue that as soon as Pimcore is in production mode, the logout route does not function anymore? Everything works well in debug (dev) mode. Cache clear does not work, nor are the routes wrong or anything... it's a miracle!

Here's my routing config:
```yml
members_auth:
    resource: '@MembersBundle/Resources/config/pimcore/routing/auth.yml'
    prefix: /{_locale}
```

Actual route (output of `bin/console debug:router`):
```log
Name                                Method          Schema       Host     Path
----------------------------------- --------------- ------------ -------- -----------------
members_user_security_logout        GET|POST        ANY          ANY      /{_locale}/logout 
```

Security settings (output of `bin/console debug:config security`):
```yml
security:
    firewalls:
        members_fe:
            logout:
                path: members_user_security_logout
                target: /
                csrf_parameter: _csrf_token
                csrf_token_id: logout
                invalidate_session: true
                delete_cookies: {  }
                handlers: {  }
```

And I'm calling it in one of my twig templates like so:
```twig
{# Input #}
<a href="{{ path('members_user_security_logout') }}">Logout</a>

{# Output #}
<a href="/de/logout">Logout</a>
```

Any help on this would be greatly appreciated! Thanks!
