### ISSUE TITLE
[EventListener] Register confirmed message is constantly being sent to the user

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#56]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Whenever a user object gets updated (e.g. moving the object in the object tree or the user is logging in) the register confirmed message will be sent.

I guess something along those [lines of code](https://github.com/dachcom-digital/pimcore-members/blob/052b5419567f0db6cca19df45524943b3db1b0b2/src/MembersBundle/EventListener/UserChangeListener.php#L50-L74) is wrong.

Pimcore Version 5.1.2 (build 192)
Members Version 2.0.1

```yml
Current configuration for "MembersBundle"
=========================================

members:
    send_admin_mail_after_register: false
    send_user_mail_after_confirmed: true
    post_register_type: confirm_by_admin
    restriction:
        enabled: false
        allowed_objects: {  }
    user:
        adapter:
            class_name: MembersUser
        initial_groups: {  }
    group:
        adapter:
            class_name: MembersGroup
    auth:
        adapter:
            class_name: null
            object_path: null
    emails:
        default:
            register_confirm: /email/register-confirm
            register_confirmed: /email/register-confirmed
            register_password_resetting: /email/password-reset
            admin_register_notification: /email/admin-register-notification
        sites: {  }
    relations:
        profile:
            form:
                type: AppBundle\Form\Type\ProfileType
                name: members_user_profile
                validation_groups:
                    - Profile
                    - Default
        registration:
            form:
                type: AppBundle\Form\Type\RegistrationType
                name: members_user_registration
                validation_groups:
                    - Registration
                    - Default
        change_password:
            form:
                type: MembersBundle\Form\Type\ChangePasswordFormType
                name: members_user_change_password_form
                validation_groups:
                    - ChangePassword
                    - Default
        resetting:
            retry_ttl: 7200
            token_ttl: 86400
            form:
                type: MembersBundle\Form\Type\ResettingFormType
                name: members_user_resetting_form
                validation_groups:
                    - ResetPassword
                    - Default

```
